version: '3'
services:
  mysql_service:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    image: openjdk:11-jre-slim
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_service:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - mynetwork
    depends_on:
      - mysql_service

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
